Repository funidata/fudis, pull requests merged in 2023-10, with the labels that each got.

#193 [IMPROVEMENT / Autocomplete single & multiselect]: Add placeholder prop
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.scss
Labels: improvement

#194 [RELEASE & DEPENDENCIES]: Release v0.0.43
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.html
  package-lock.json
  package.json
Labels: dependencies

#197 [Dropdown & DD]: form placeholder styles and dd whitespace fix
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.spec.ts
Labels: bug fix

#191 [HeadingComponent]: Add responsive heading sizes
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
Labels: improvement

#188 [Grid]: Documentation and unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-api/grid-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-utils.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid/grid.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid/grid.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/grid/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/grid/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/types/grid.ts
  ngx-fudis/projects/ngx-fudis/utilities/tests/utilities.ts
Labels: improvement

#196 [Rem converter]: Support for different base font-sizes
  ngx-fudis/.storybook/main.js
  ngx-fudis/.stylelintrc.json
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/app.scss
  ngx-fudis/projects/dev/src/styles.scss
  ngx-fudis/projects/documentation/introduction/GettingStarted.stories.mdx
  ngx-fudis/projects/ngx-fudis/karma.conf.js
  ngx-fudis/projects/ngx-fudis/karma.style.css
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-utils.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/gridUtils.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/grid/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/types/spacing.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/rem-converter.ts
  ngx-fudis/projects/ngx-fudis/style.scss
Labels: feature

#199 [Checkbox Group]: Part 2 - Documentation, testing and general cleaning
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/classes.scss
Labels: feature

#200 [BadgeComponent]: Add CSS display
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/tokens.scss
Labels: bug fix

#202 [FOCUS SERVICE]: add ignore utilities
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.ts
Labels: improvement

#204 [chore]: Fix release note config
  .github/release.yml
Labels: dependencies

#205 [chore]: Update release notes commit message
  .github/workflows/release.yaml
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  scripts/version_sub_projects.sh
Labels: chore

#206 [CHORE]: Release pipeline documentation
  ngx-fudis/projects/documentation/development/CreatingAComponent.stories.mdx
  ngx-fudis/projects/documentation/development/CreatingARelease.stories.mdx
  ngx-fudis/projects/documentation/development/Releases.stories.mdx
Labels: chore

#208 [CHECKBOX GROUP / VALIDATORS]: fudis group validators with observable messages
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/dev/src/assets/i18n/en.json
  ngx-fudis/projects/dev/src/assets/i18n/fi.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
Labels: breaking change, improvement

#207 [CHORE]: Add current package version to Storybook and create release script
  .github/release.yml
  .github/workflows/storybook_publish.yaml
  ngx-fudis/.storybook/getVersion.js
  ngx-fudis/.storybook/main.js
  ngx-fudis/.storybook/preview.js
  ngx-fudis/package.json
  ngx-fudis/projects/documentation/development/CreatingARelease.stories.mdx
  package.json
  scripts/release.sh
Labels: chore

#209 Bump to version v0.1.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
Labels: exclude from release notes

#210 [Validators / Checkbox Group]: Renaming & markAsTouched logic changes
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/documentation/development/CreatingARelease.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: bug fix, breaking change

#211 Bump to version v0.1.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
Labels: exclude from release notes

#212 [Breadcrumbs]: Fix broken unit tests and some cleaning
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
Labels: chore

#214 Push only one tag from release script to avoid polluting origin with bad local tags
  package.json
Labels: exclude from release notes

#215 [Checkbox Group]: Tests
  ngx-fudis/projects/ngx-fudis/karma.conf.js
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu-item/dropdown-menu-item.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/mixins.scss
Labels: chore

#216 [Link]: Underline appearance enhancement
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/readme.mdx
Labels: improvement
