Repository funidata/fudis, pull requests merged in 2023-12, with the labels that each got.

#230 Bump to version v0.1.3
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
Labels: exclude from release notes

#229 [Dialog, Form]: Form layout remake if inside dialog
  cypress/cypress-visual-report/cypress-visual-report.html
  cypress/cypress-visual-report/report.json
  cypress/cypress-visual-screenshots/baseline/dialog.cy.ts/desktop-1.png
  cypress/cypress-visual-screenshots/baseline/dialog.cy.ts/desktop-2.png
  cypress/cypress-visual-screenshots/baseline/dialog.cy.ts/desktop-3.png
  cypress/cypress-visual-screenshots/baseline/dialog.cy.ts/mobile-1.png
  cypress/cypress-visual-screenshots/baseline/dialog.cy.ts/mobile-2.png
  cypress/cypress-visual-screenshots/baseline/dialog.cy.ts/mobile-3.png
  cypress/e2e/components/dialog.cy.ts
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-content.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/actions/actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
Labels: improvement

#232 [ErrorSummaryService]: Refactor ErrorSummaryService functions to public and private
  ngx-fudis/.storybook/preview.js
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: improvement

#236 [Validator error message]: Unit tests and internal documentation
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
Labels: chore
