Repository funidata/fudis, pull requests merged in 2023-11, with the labels that each got.

#213 [Breadcrumbs]: Documentation, aria-label construction, responsiveness, refactoring
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/assets/i18n/en.json
  ngx-fudis/projects/dev/src/assets/i18n/fi.json
  ngx-fudis/projects/ngx-fudis/karma.conf.js
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translationKeys.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/id.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: feature

#217 [DEPS]: Update deps 2023-10-31
  ngx-fudis/.stylelintrc.json
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
Labels: dependencies

#218 [Datepicker]: Add missing translation keys for screenreader
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/utilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translationKeys.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
Labels: improvement

#219 [Id Service]: Refactor idService usage
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
Labels: chore

#220 [Alert Group]: Initiate aria-label only when there are 1 or more alert present
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.html
Labels: bug fix

#221 [Link]: Change color to primary-dark
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
Labels: improvement

#223 [DEPS]: Update
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.spec.ts
Labels: dependencies
