Repository funidata/fudis, pull requests merged in 2024-01, with the labels that each got.

#237 [Validators]: Unit tests and documentation for Fudis Validators
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
Labels: chore

#239 Require all linting checks to pass in CI and fix existing linting errors
  .github/workflows/run_tests.yaml
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test.component.ts
  ngx-fudis/projects/ngx-fudis/schematics/ng-add/index.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu-item/dropdown-menu-item.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu-item/dropdown-menu-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-date-adapter.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/actions/actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/dropdown-base/dropdown-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid/grid.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/palette.scss
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/areObjectsDeepEquals.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/groupValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
  ngx-fudis/projects/ngx-fudis/utilities/tests/utilities.ts
  ngx-fudis/types/mdx.d.ts
Labels: chore, exclude from release notes

#241 Include translation assets in sandbox build
  ngx-fudis/angular.json
Labels: chore, exclude from release notes

#238 [Error Summary]: Logic tweaking, unit tests and documentation
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/dev/src/app/transloco-loader.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-date-adapter.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/selectUtilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/actions/actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/content/content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/header/header.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/notifications/notifications.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid/grid.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/tests/utilities.ts
Labels: breaking change, chore

#242 [Validators]: Convert Datepicker and Date Range ngMaterial validators to FudisValidators
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/arrow-big.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/calendar.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/magic-wand.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/picker.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/print.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/rosette.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/seats.svg
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-date-adapter.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/utilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translationKeys.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
Labels: breaking change

#244 [Select & SelectOption]: Unit Tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
Labels: chore

#243 [DEPS]: Update dependencies
  cypress/tsconfig.json
  ngx-fudis/.storybook/tsconfig.json
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/colors/readme.stories.mdx
  ngx-fudis/tsconfig.json
  package-lock.json
  package.json
Labels: dependencies, exclude from release notes

#245 [SelectDropdown & DropdownBase]: Unit Tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/dropdown-base/dropdown-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/dropdown-base/dropdown-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
Labels: chore

#248 [SelectOptionBaseDirective]:Unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/tests/utilities.ts
Labels: chore

#246 [Select]: Adjust autocomplete no results found logic
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
Labels: bug fix

#247 [getValidators]: add tests
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
Labels: exclude from release notes

#249 [SelectGroupComponent]: Unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.ts
Labels: chore

#252 [SelectBaseDirective]: Unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/selectUtilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
Labels: chore

#251 [Dialog]: Add dialog size 'xl'
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx
Labels: improvement
