Repository funidata/fudis, pull requests merged in 2024-02, with the labels that each got.

#257 [Select]: Autocomplete unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.spec.ts
Labels: chore

#250 [Select]: Multiselect unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-chip-list/multiselect-chip-list.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-chip-list/multiselect-chip-list.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts
Labels: chore

#259 Fix problems with Prettier's parsing of tsconfig.json files
  .prettierrc
  .prettierrc.yaml
  cypress/tsconfig.json
  ngx-fudis/.storybook/tsconfig.json
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/tsconfig.json
  package-lock.json
  package.json
Labels: exclude from release notes

#258 [InputBaseDirective, FieldsetBaseDirective]: Unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/classes.scss
Labels: chore

#253 [Documentation]: Update and clean (Jan2024)
  ngx-fudis/.storybook/preview.js
  ngx-fudis/projects/documentation/development/ComponentChecklist.stories.mdx
  ngx-fudis/projects/documentation/development/CreatingAComponent.stories.mdx
  ngx-fudis/projects/documentation/development/CreatingARelease.stories.mdx
  ngx-fudis/projects/documentation/development/DevelopmentEnvironment.stories.mdx
  ngx-fudis/projects/documentation/development/ProjectStructure.stories.mdx
  ngx-fudis/projects/documentation/development/TestingPractises.stories.mdx
  ngx-fudis/projects/documentation/introduction/GettingStarted.stories.mdx
  ngx-fudis/projects/documentation/introduction/Introduction.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/borders/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/borders/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/breakpoints/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/grid/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/z-index/readme.stories.mdx
Labels: exclude from release notes

#263 [Autocomplete, Dropdown, RadioButtonGroup, InputWithLanguageOptions]: Cleaning for ver 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select-selected-item-chip/autocomplete-multi-select-selected-item-chip.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select-selected-item-chip/autocomplete-multi-select-selected-item-chip.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select-selected-item-chip/autocomplete-multi-select-selected-item-chip.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select-selected-item-chip/autocomplete-multi-select-selected-item-chip.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/autocomplete-multi-select.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/autocomplete-multi-select/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/dropdown.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/dropdown/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#262 [Form]: Unit tests and Storybook documentation
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/readme.mdx
Labels: chore

#260 [ErrorMsg & GroupErrorMsg, Guidance component]: Error message removal and Guidance component Unit tests
  ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
Labels: breaking change, chore

#264 [LanguageBadge, LanguageBadgeGroup]: Checking and cleaning
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: exclude from release notes

#266 [Description List]: Cleaning for ver 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#268 [Badge, Breadcrumbs, Button]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
Labels: exclude from release notes

#267 [AlertGroupComponent, AlertComponent, FudisAlertService]: Comment out and mark TODOs
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/alert/alert.service.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#265 [FieldSet]: Unit tests and documentation
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
Labels: chore

#270 [Text Input, Text Area]: Cleaning for 1.0, removed min/max Inputs
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
Labels: breaking change

#269 [Guidance, Error Message, Validator Error Message]Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: exclude from release notes

#272 [Dialog]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
Labels: exclude from release notes

#273 [Expandable]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.ts
Labels: exclude from release notes

#274 [DropdownMenu & DropdownMenuItem]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/dropdown-item-base/dropdown-item-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/dropdown-item-base/dropdown-item-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#278 [Storybook, Deps]: Hotfix for restoring argtypes
  ngx-fudis/.storybook/compodoc.tsconfig.json
  ngx-fudis/.storybook/main.js
  ngx-fudis/angular.json
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/colors/readme.stories.mdx
Labels: dependencies, exclude from release notes

#275 [Tooltip, Spacing, Content Projection, Dialog and Grid Directives]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/actions/actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/content/content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/header/header.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/notifications/notifications.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-api/grid-api.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-item/grid-item.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-utils.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid/grid.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing-api/spacing-api.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#276 [Utilities]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/areObjectsDeepEquals.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/breakpoint/breakpoint-utils.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/groupValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/rem-converter.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/tests/utilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/untilDestroyed.ts
Labels: exclude from release notes

#279 [Breakpoint, Focus, Grid and Error Summary Services]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/breakpoint/breakpoint.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/grid/grid.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/grid/grid.service.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: exclude from release notes

#280 [Section & InputWithLanguageOptions]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#277 [Id, Translation and LanguageBadgeGroup Services]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/language-badge-group/language-badge-group.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/language-badge-group/language-badge-group.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translationKeys.ts
Labels: exclude from release notes

#282 [Storybook]: Configuring ArgTypes filtering
  ngx-fudis/.storybook/compodoc.tsconfig.json
  ngx-fudis/.storybook/preview.js
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-content.component.ts
  ngx-fudis/projects/documentation/development/SetupVSCode.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/borders/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/breakpoints/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/z-index/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: breaking change

#284 [Icon, Body Text, Header]: Check for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: exclude from release notes

#283 [Datepicker & DateRange]: Checking for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-date-adapter.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-header/datepicker-custom-header.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-header/datepicker-custom-header.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/datepicker-custom-header/datepicker-custom-header.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/utilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#281 [Grid, GridItem, Footer & Label]: Check for 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-api/grid-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/grid.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: exclude from release notes

#285 [Checkbox, CheckboxGroup, Link, Notification]: Check for Fudis 1.0
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: breaking change

#286 [Icon]: Change color Input names
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/types/icons.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: breaking change

#287 [BreadCrumbsComponent, CheckboxGroupComponent]: API and controls check for Breadcrumbs and Checkbox Group
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: exclude from release notes

#289 [Link, Notification]: API check
  ngx-fudis/.storybook/main.js
  ngx-fudis/projects/ngx-fudis/src/lib/assets/images/favicon.ico
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: breaking change

#288 [TextInput, TextArea, InputBaseDirective, Heading, BodyText]: Remove Required input & checking for 1.0
  .husky/pre-push
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/classes.scss
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: breaking change

#291 [Link]: Parse Link title for better line break alignment
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts
Labels: exclude from release notes

#271 Visual regression tests with Playwright
  .github/workflows/build_image.yaml
  .github/workflows/run_tests.yaml
  compose.yaml
  ngx-fudis/projects/documentation/development/CommandReference.stories.mdx
  ngx-fudis/projects/documentation/development/DevelopmentEnvironment.stories.mdx
  ngx-fudis/projects/documentation/development/TestingPractises.stories.mdx
  package.json
  scripts/version_sub_projects.sh
  test/.dockerignore
  test/.gitignore
  test/Dockerfile
  test/package-lock.json
  test/package.json
  test/playwright.config.ts
  test/visual-regression/badge.spec.ts
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-Mobile-Chrome-linux.png
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-Mobile-Safari-linux.png
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-chromium-linux.png
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-firefox-linux.png
  test/visual-regression/badge.spec.ts-snapshots/badge-default-1-webkit-linux.png
  test/visual-regression/multiselect.spec.ts
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-Mobile-Chrome-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-Mobile-Safari-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-chromium-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-firefox-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/default-1-webkit-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-Mobile-Chrome-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-Mobile-Safari-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-chromium-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-firefox-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/focused-1-webkit-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-Mobile-Chrome-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-Mobile-Safari-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-chromium-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-firefox-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/option-selected-1-webkit-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-Mobile-Chrome-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-Mobile-Safari-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-chromium-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-firefox-linux.png
  test/visual-regression/multiselect.spec.ts-snapshots/selected-and-blurred-1-webkit-linux.png
Labels: exclude from release notes

#294 [Button,Expandable,Tooltip,Dialog Component & Service]:API Checked
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu-item/dropdown-menu-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: exclude from release notes

#292 [Badge, Footer]: API check
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/content-projection/content/content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#293 [Form, Error Message, Error Summary Service]: API check
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
Labels: exclude from release notes

#296 [Select]: API check
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/common.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/selectUtilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-chip-list/multiselect-chip-list.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: exclude from release notes

#299 [Error message, Error Summary and Form]:Added Storybook controls
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: exclude from release notes

#298 [Translation Service]: Documentation
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/readme.stories.mdx
Labels: chore

#302 Bump to version v0.2.3-rc.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#303 Bump to version v0.2.4-rc.0
  .github/workflows/release.yaml
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes
