Repository funidata/fudis, pull requests merged in 2024-03, with the labels that each got.

#305 [Deps]: Update and adjust versions
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
Labels: dependencies

#304 [Button, Expandable, ErrorMessage]: Life cycle cleaning
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.stories.ts
Labels: exclude from release notes

#300 [Documentation, Icon]: Check for 1.0, Remove two icons
  ngx-fudis/.storybook/preview.js
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/documentation/development/CodeLintingAndFormatting.stories.mdx
  ngx-fudis/projects/documentation/development/DevOps.stories.mdx
  ngx-fudis/projects/documentation/development/DevelopmentEnvironment.stories.mdx
  ngx-fudis/projects/documentation/development/GettingStarted.stories.mdx
  ngx-fudis/projects/documentation/development/dsPractises/ComponentChecklist.stories.mdx
  ngx-fudis/projects/documentation/development/dsPractises/CreatingAComponent.stories.mdx
  ngx-fudis/projects/documentation/development/dsPractises/NamingConventions.stories.mdx
  ngx-fudis/projects/documentation/development/dsPractises/ProjectStructure.stories.mdx
  ngx-fudis/projects/documentation/development/dsPractises/TestingPractises.stories.mdx
  ngx-fudis/projects/documentation/development/dsPractises/WaysOfWorking.stories.mdx
  ngx-fudis/projects/documentation/development/tooling/CommandReference.stories.mdx
  ngx-fudis/projects/documentation/development/tooling/CreatingARelease.stories.mdx
  ngx-fudis/projects/documentation/development/tooling/GitAndGitHubConventions.stories.mdx
  ngx-fudis/projects/documentation/development/tooling/SetupVSCode.stories.mdx
  ngx-fudis/projects/documentation/introduction/GettingStarted.stories.mdx
  ngx-fudis/projects/documentation/introduction/Introduction.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/double-chevron-left.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/double-chevron-right.svg
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/breakpoints/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/colors/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/focus/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/typography.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/types/icons.ts
Labels: breaking change

#306 [Deps]: adjust peerdeps
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
Labels: dependencies

#308 DS-273: Added UI Router support
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.module.ts
  ngx-fudis/projects/dev/src/app/components/examplePage.component.html
  ngx-fudis/projects/dev/src/app/components/examplePage.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
Labels: improvement

#309 Bump to version v0.2.4
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#312 [ErrorSummary, TextInput, TextArea]: Improvements to Form and Error Summary syncing
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
Labels: improvement

#313 [Link & Link Api Directive]: Refactoring Link component
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.module.ts
  ngx-fudis/projects/dev/src/app/components/examplePage.component.html
  ngx-fudis/projects/dev/src/app/components/examplePage.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link-api/link-api.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link-api/link-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link-directive.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: improvement

#316 [Form, ErrorSummary]: Add onClick link type to support non Angular Router apps
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
Labels: improvement

#318 [DialogService]: Close function with parameter to be passed back to the component
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/app.module.ts
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
Labels: improvement

#320 Bump to version v0.2.7
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#321 [Link]: Bug fix on external link parsing
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.ts
Labels: bug fix

#319 [Form components and services]: Update docs, comments and adjust internal renaming
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary-component.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary-service.docs.mdx
Labels: exclude from release notes

#323 [FudisSelectOption, FudisCheckboxGroup]: Generic typing
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/common.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/selectUtilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-chip-list/multiselect-chip-list.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-chip-list/multiselect-chip-list.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
Labels: improvement

#324 [NgMaterial theme]: Typography size conversion
  ngx-fudis/projects/ngx-fudis/src/lib/theme/fudis-theme.scss
Labels: bug fix

#325 [CheckboxGroup]: Add support for FormArray
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-array.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
Labels: improvement

#326 Bump to version v0.2.8
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#328 [CheckboxGroup]: Remove required props
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
Labels: bug fix

#329 Bump to version v0.2.9
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#330 [Checkbox, CheckboxGroup]: add formControl option to Checkbox
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
Labels: improvement

#317 [Fieldset]:Rename title property & cleanup
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-array.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group-with-form-group.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.docs.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/common.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/readme.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
  test/visual-regression/multiselect.spec.ts
Labels: breaking change

#331 [Text Input]: Fix character indicator for maxLength validator
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
Labels: bug fix

#332 Bump to version v1.0.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#333 [Ui-router]: Remove repedencies
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
Labels: dependencies

#335 [Dialog]: Fixed Dialog bugs
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/ring-close-fill.svg
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-Mobile-Chrome-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-Mobile-Safari-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-chromium-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-firefox-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/validation-4-errors-webkit-linux.png
Labels: bug fix

#340 Bump to version v1.1.0-rc.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#343 Bump to version v1.1.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes
