Repository funidata/fudis, pull requests merged in 2024-10, with the labels that each got.

#450 [SCSS]: Style import optimizations
  ngx-fudis/projects/dev/src/styles.scss
  ngx-fudis/projects/documentation/introduction/GettingStarted.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/theme/palette.scss
  ngx-fudis/projects/ngx-fudis/style.scss
Labels: breaking change

#452 Bump to version v3.0.0-rc.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#454 [SelectBase]: Undefined inputRef error
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
Labels: bug fix

#457 Bump to version v3.0.0-rc.2
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#459 Bump to version v3.0.0-rc.3
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#461 [Footer]: Fix focus area
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/readme.mdx
  test/visual-regression/footer.spec.ts-snapshots/footer-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/footer.spec.ts-snapshots/footer-1-Mobile-Chrome-linux.png
  test/visual-regression/footer.spec.ts-snapshots/footer-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/footer.spec.ts-snapshots/footer-1-Mobile-Safari-linux.png
  test/visual-regression/footer.spec.ts-snapshots/footer-1-chromium-linux.png
  test/visual-regression/footer.spec.ts-snapshots/footer-1-firefox-linux.png
  test/visual-regression/footer.spec.ts-snapshots/footer-1-webkit-linux.png
Labels: bug fix

#462 [TextFieldComponentBaseDirective]: New internal Directive and nullControlOnEmptyString property
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/text-field-component-base/text-field-component-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/text-field-component-base/text-field-component-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
Labels: improvement

#463 Bump to version v3.0.0-rc.4
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#456 [Security Information Management]:Documentation
  ngx-fudis/projects/documentation/development/InformationSecurityManagement.mdx
Labels: chore

#464 [RadioButton]: Long label breaks layout
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.scss
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-Mobile-Chrome-linux.png
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-Mobile-Safari-linux.png
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-chromium-linux.png
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-firefox-linux.png
  test/visual-regression/radio-button-group.spec.ts-snapshots/disabled-1-init-webkit-linux.png
Labels: bug fix

#465 [DescriptionList]: Clean documentation
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-docs.mdx
Labels: chore

#466 [Deprecated Autocomplete]: Remove component from the library
  ngx-fudis/.storybook/main.js
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: exclude from release notes

#467 [AlertGroup]: Missing documentation about template usage
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.html
Labels: chore

#468 [Form Components]: Add "disabled" Input
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-common-api/form-common-api.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-common-api/form-common-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/classes.scss
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  test/visual-regression/text-input.spec.ts-snapshots/disabled-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/text-input.spec.ts-snapshots/disabled-Mobile-Chrome-linux.png
  test/visual-regression/text-input.spec.ts-snapshots/disabled-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/text-input.spec.ts-snapshots/disabled-Mobile-Safari-linux.png
  test/visual-regression/text-input.spec.ts-snapshots/disabled-chromium-linux.png
  test/visual-regression/text-input.spec.ts-snapshots/disabled-firefox-linux.png
  test/visual-regression/text-input.spec.ts-snapshots/disabled-webkit-linux.png
Labels: improvement

#469 Bump to version v3.0.0-rc.5
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#472 [Typography]: Unify size syntax
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/tokens.scss
Labels: breaking change

#471 [Datepicker, Tooltip]: Angular Material based components not reflecting all styles correctly in customer app
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/ngMaterial-theme.scss
Labels: bug fix

#473 Bump to version v3.0.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#470 [Select, Multiselect]: New input properties 'autocompleteFilter' and 'autocompleteNoResultsText' with Storybook examples
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-common.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/examples/backend-simulation-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/examples/multiselect-backend-simulation.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/examples/multiselect-showcase.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/examples/select-backend-simulation.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/examples/select-showcase.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select-showcase.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
  test/visual-regression/date-range.spec.ts
  test/visual-regression/description-list_grid-disabled.spec.ts
  test/visual-regression/description-list_grid-enabled.spec.ts
  test/visual-regression/multiselect-autocomplete-filter-false.spec.ts
  test/visual-regression/multiselect.spec.ts
  test/visual-regression/select-autocomplete-filter-false.spec.ts
  test/visual-regression/select-autocomplete.spec.ts
  test/visual-regression/select-dropdown.spec.ts
  test/visual-regression/tooltip.spec.ts
Labels: improvement

#474 [Maintenance]: Missing information in npmjs website
  ngx-fudis/projects/ngx-fudis/package.json
  package.json
Labels: exclude from release notes

#475 [DescriptionList]: Add min-height for regular DescriptionListItemDetails element
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.scss
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-Mobile-Chrome-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-Mobile-Safari-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-chromium-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-firefox-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-10-lang-focus-fi-webkit-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-Mobile-Chrome-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-Mobile-Safari-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-chromium-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-firefox-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-11-lang-focus-en-webkit-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-6-clicked-en-badge-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-6-clicked-en-badge-Mobile-Chrome-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-6-clicked-en-badge-Mobile-Safari-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-6-clicked-en-badge-chromium-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-7-clicked-sv-badge-chromium-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-Mobile-Chrome-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-Mobile-Safari-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-chromium-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-firefox-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/regular-9-lang-focus-sv-webkit-linux.png
Labels: bug fix
