Repository funidata/fudis, pull requests merged in 2024-06, with the labels that each got.

#373 [Translations]: Cleaning and unifying translation usage
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-icons/select-icons.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-icons/select-icons.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/untilDestroyed.ts
Labels: chore

#372 Publish docs to AWS S3 bucket
  .github/workflows/complete_storybook_deployment.yaml
  .github/workflows/delete_branch_docs.yaml
  .github/workflows/publish_docs_from_pr.yaml
  .github/workflows/release.yaml
  .github/workflows/remove_old_storybooks.yaml
  .github/workflows/run_tests.yaml
  .github/workflows/storybook_publish.yaml
  .github/workflows/storybook_publish_branch.yaml
  .github/workflows/storybook_publish_version.yaml
  README.md
  compose.yaml
  ngx-fudis/.storybook/getVersion.js
  ngx-fudis/.storybook/main.js
  ngx-fudis/.storybook/preview.js
  ngx-fudis/package.json
Labels: exclude from release notes

#382 [Form & Section]: Change titleLevel property and badge added to section
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select-showcase.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
  test/visual-regression/section.spec.ts-snapshots/section-default-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-1-Mobile-Chrome-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-1-Mobile-Safari-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-1-chromium-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-1-firefox-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-1-webkit-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-Mobile-Chrome-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-Mobile-Safari-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-chromium-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-firefox-linux.png
  test/visual-regression/section.spec.ts-snapshots/section-default-2-webkit-linux.png
Labels: breaking change

#381 [Link]: Clarify documentation
  ngx-fudis/projects/ngx-fudis/_index.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link-directive.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/theme/fudis-theme.scss
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-chromium-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-firefox-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-webkit-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-3-before-submit-chromium-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-3-before-submit-firefox-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-3-before-submit-webkit-linux.png
Labels: improvement

#384 [Form, ErrorSummary]: Remove errorSummaryLinkType
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/dialog-test/dialog-test-content/dialog-test-form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
Labels: breaking change

#386 [Workspace settings]: add angular ng-template to recommendations
  settings/.vscode/extensions.json
Labels: exclude from release notes

#388 [Description List Details, Description List Term]: Change input name 'textContent' to 'contentText'"
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select-showcase.stories.ts
Labels: breaking change

#397 Bump to version v2.0.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#398 Fix docs deploy workflow failing when editing release notes programmatically and set low TTL for root index.html cache
  .github/workflows/release.yaml
Labels: chore, exclude from release notes

#399 Reduce TTL for PR build docs cache also
  .github/workflows/publish_docs_from_pr.yaml
Labels: chore, exclude from release notes

#400 Update vulnerable ip version and bind dependencies to minor versions
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
Labels: dependencies

#402 [Notification]: Revert CSS width to its original state
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-dynamic-validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  test/visual-regression/form-dynamic-validators.spec.ts
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Chrome-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Safari-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-chromium-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-firefox-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-webkit-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Chrome-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Safari-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-chromium-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-firefox-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-webkit-linux.png
  test/visual-regression/notification.spec.ts-snapshots/with-multiple-child-components-1-chromium-linux.png
  test/visual-regression/notification.spec.ts-snapshots/with-multiple-child-components-1-firefox-linux.png
  test/visual-regression/notification.spec.ts-snapshots/with-multiple-child-components-1-webkit-linux.png
Labels: bug fix

#403 [Dialog, TextArea]: Fix double scrollbar and validity observable subscibe
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  test/visual-regression/dialog.spec.ts-snapshots/form-1-init-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-3-before-submit-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/grid-1-init-Mobile-Safari-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/grid-1-init-webkit-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/grid-2-content-focus-Mobile-Safari-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/grid-2-content-focus-webkit-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/grid-3-content-scrolled-Mobile-Safari-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/grid-3-content-scrolled-webkit-linux.png
Labels: bug fix

#404 Bump to version v2.0.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes
