Repository funidata/fudis, pull requests merged in 2024-08, with the labels that each got.

#407 [DescriptionList]: Add font-weight for compact list colon
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.scss
Labels: bug fix

#409 [Dialog]: Change Storybook example headings to h1
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.stories.ts
Labels: chore

#414 [Accessibility]: Miscellaneous fixes
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.html
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-Mobile-Chrome-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-Mobile-Safari-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-chromium-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-firefox-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-1-webkit-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-Mobile-Chrome-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-Mobile-Safari-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-chromium-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-firefox-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-2-webkit-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-Mobile-Chrome-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-Mobile-Safari-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-chromium-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-firefox-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-with-service-3-webkit-linux.png
Labels: chore

#413 [Datepicker]: Accessibility fixes (disabled state, color contrast)
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/ngMaterial-theme.scss
  test/visual-regression/datepicker.spec.ts
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-Mobile-Chrome-linux.png
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-Mobile-Safari-linux.png
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-chromium-linux.png
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-firefox-linux.png
  test/visual-regression/datepicker.spec.ts-snapshots/disabled-2-focus-webkit-linux.png
Labels: bug fix

#415 [Checkbox, CheckboxGroup]: Accessibility fixes (disabled state, aria-describedby)
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-dynamic-validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  test/visual-regression/checkbox-group.spec.ts
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-Mobile-Chrome-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-Mobile-Safari-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-chromium-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-firefox-linux.png
  test/visual-regression/checkbox-group.spec.ts-snapshots/disabled-2-focused-webkit-linux.png
Labels: bug fix

#412 [Documentation]: Yarn link instructions
  ngx-fudis/.storybook/preview.js
  ngx-fudis/package.json
  ngx-fudis/projects/documentation/development/dsPractises/CreatingAComponent.stories.mdx
  ngx-fudis/projects/documentation/development/tooling/CreatingARelease.stories.mdx
  ngx-fudis/projects/documentation/development/tooling/TestingLocalChangesWithSymlink.stories.mdx
Labels: chore

#416 Bump to version v2.1.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#419 [Spacing]: Helper classes
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/classes.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/lib/theme/display-theme.scss
Labels: feature

#421 [CSS Helper Classes]:New feature
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid-item/grid-item.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing-api/spacing-api.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing-api/spacing-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/spacing/spacing.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/CSS-helper-classes.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/CSS-helper-classes.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/classes.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/spacing/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/lib/theme/display-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
  test/visual-regression/CSS-Helper-class.spec.ts
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-Mobile-Chrome-linux.png
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-Mobile-Safari-linux.png
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-chromium-linux.png
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-firefox-linux.png
  test/visual-regression/CSS-Helper-class.spec.ts-snapshots/responsive-margins-and-paddings-1-webkit-linux.png
Labels: feature
