Repository funidata/fudis, pull requests merged in 2024-09, with the labels that each got.

#425 [Language Badge Group]: Introduce Language Badge Group Component to public API
  ngx-fudis/.storybook/preview.js
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
  test/visual-regression/language-badge-group.spec.ts
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-Mobile-Chrome-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-Mobile-Safari-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-chromium-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-firefox-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-Mobile-Chrome-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-Mobile-Safari-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-chromium-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-firefox-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-en-webkit-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-Mobile-Chrome-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-Mobile-Safari-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-chromium-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-firefox-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-fi-webkit-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-Mobile-Chrome-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-Mobile-Safari-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-chromium-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-firefox-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-focus-sv-webkit-linux.png
  test/visual-regression/language-badge-group.spec.ts-snapshots/language-badge-group-webkit-linux.png
Labels: feature

#426 Bump to version v2.2.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#429 [Autocomplete]:Deprecated
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/autocomplete.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/autocomplete/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: exclude from release notes

#433 [Section]:Removed marginTop and Bottom
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
Labels: breaking change

#434 [Fieldset]:Removed marginTop and Bottom Input
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/readme.mdx
Labels: breaking change

#436 [Form]: Removed marginTop and Bottom input
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-dynamic-validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select-showcase.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: breaking change

#432 [Heading]: Removed marginBottom property
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/display-theme.scss
Labels: breaking change

#438 [BreakingChange] [Validators]: Refactor Fudis.atLeastOneRequired validator name to Fudis.oneRequired
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-dynamic-validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/input-with-language-options/input-with-language-options.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/getValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/groupValidators.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
Labels: breaking change

#427 [Alert, Alert Group, Alert Service]: New components and service
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/assets/i18n/en.json
  ngx-fudis/projects/dev/src/assets/i18n/fi.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/alert/alert.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/alert/alert.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
  test/visual-regression/alert-group.spec.ts
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-webkit-linux.png
Labels: feature

#439 [HorizontalRule]: New component, remove existing style class and mixin
  ngx-fudis/.storybook/preview.js
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-dynamic-validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/classes.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/display-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.stories.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-Mobile-Chrome-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-Mobile-Safari-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-chromium-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-firefox-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-1-submit-with-errors-webkit-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-Mobile-Chrome-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-Mobile-Safari-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-chromium-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-firefox-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-2-submit-without-errors-webkit-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Chrome-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-Mobile-Safari-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-chromium-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-firefox-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-3-submit-with-invalid-data-webkit-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Chrome-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-Mobile-Safari-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-chromium-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-firefox-linux.png
  test/visual-regression/form-dynamic-validators.spec.ts-snapshots/dynamic-4-submit-after-removed-validators-webkit-linux.png
  test/visual-regression/horizontal-rule.spec.ts
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-Mobile-Chrome-linux.png
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-Mobile-Safari-linux.png
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-chromium-linux.png
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-firefox-linux.png
  test/visual-regression/horizontal-rule.spec.ts-snapshots/horizontal-rule-1-webkit-linux.png
Labels: breaking change

#443 Bump to version v3.0.0-rc.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#446 [Checkbox]: Changed checkbox height to min height
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.scss
Labels: bug fix

#445 [RadioButton, Checkbox]: Unify output namings, refactor radio button and checkbox blur and change events
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
Labels: breaking change
