Repository funidata/fudis, pull requests merged in 2024-05, with the labels that each got.

#362 [Grid, FormSubmit]: Adjustments for Safari
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.directive.ts
  test/visual-regression/grid-item.spec.ts-snapshots/columns-Mobile-Chrome-linux.png
  test/visual-regression/grid-item.spec.ts-snapshots/columns-Mobile-Safari-linux.png
  test/visual-regression/grid-item.spec.ts-snapshots/responsive-columns-Mobile-Chrome-linux.png
  test/visual-regression/grid-item.spec.ts-snapshots/responsive-columns-Mobile-Safari-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-min-content-Mobile-Chrome-linux.png
  test/visual-regression/grid.spec.ts-snapshots/grid-min-content-Mobile-Safari-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-chromium-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-webkit-linux.png
Labels: bug fix

#363 Bump to version v1.3.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#368 [Typography]: Add table caption mixin
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/typography.stories.mdx
  ngx-fudis/projects/ngx-fudis/style.scss
Labels: improvement
