Repository funidata/fudis, pull requests merged in 2024-11, with the labels that each got.

#477 [ErrorSummary]: Fixing sync issues with TranslationService
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/app.component.ts
  ngx-fudis/projects/dev/src/app/app.module.ts
  ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.html
  ngx-fudis/projects/dev/src/app/components/dropdownExamples.component.ts
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary-component.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  test/visual-regression/form-dynamic-validators.spec.ts
Labels: bug fix

#480 [Dependencies]: Update devDependencies
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
Labels: dependencies

#481 Bump to version v3.1.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#478 [ErrorMessageComponent, ValidatorErrorMessageComponent]: ChangeDetection Strategy to OnPush
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
Labels: chore

#482 [Chore]: Fix Fudis homepage in project's package.json
  ngx-fudis/projects/ngx-fudis/package.json
Labels: chore

#484 [Services]: Refactoring Inject rules
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/badge/badge.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-icons/select-icons.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/horizontal-rule/horizontal-rule.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/dialog/dialog-directives.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/control-component-base/control-component-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/group-component-base/group-component-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/alert/alert.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/alert/alert.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.ts
Labels: chore

#483 [Select, Multiselect]: Adjust visible label update logic for language changes
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/dev/src/assets/i18n/en.json
  ngx-fudis/projects/dev/src/assets/i18n/fi.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert/alert.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-common-api/form-common-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid-utils.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/gridUtils.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/spacing.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/rem-converter.ts
  test/visual-regression/error-summary.spec.ts
Labels: bug fix

#488 DS-398: Fixed aria-invalid state
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button/radio-button.component.html
Labels: bug fix

#491 Bump to version v3.2.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#494 Bump to version v3.2.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#493 [DescriptionList]: Screen reader detects content that should be hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.html
  test/visual-regression/description-list_grid-enabled.spec.ts-snapshots/description-list-compact-with-sub-components-1-Mobile-Safari-linux.png
Labels: bug fix
