Repository funidata/fudis, pull requests merged in 2024-04, with the labels that each got.

#344 [HeadingComponent]: Adjust encapsulation and CSS grid-column logic
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/heading/heading.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: chore

#345 [Deps]: Update 04/2024
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
Labels: dependencies

#342 [DescriptionList]: Expose DL component family for public API, add support for single DL Item and for multiple DD elements
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/readme.hidden
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-group/select-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  ngx-fudis/projects/ngx-fudis/src/lib/types/id.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: feature

#346 [Icon]: Refactor SVGs to HTML template
  ngx-fudis/.storybook/main.js
  ngx-fudis/angular.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/breadcrumbs/breadcrumbs-item/breadcrumbs-item.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  test/visual-regression/icon.spec.ts
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-Mobile-Chrome-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-Mobile-Safari-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-chromium-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-firefox-linux.png
  test/visual-regression/icon.spec.ts-snapshots/all-icons-1-webkit-linux.png
Labels: chore

#348 [Focus Service, Translation Service]: Tests and refactoring
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/link/link.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/input-base/input-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link-api/link-api.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/focus/focus.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/testData.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/language-badge-group/language-badge-group.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/language-badge-group/language-badge-group.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/id.ts
Labels: chore

#349 [Translation Service]: Unit tests, docs update and minor refactoring and renaming
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/readme.stories.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translation.service.ts
Labels: chore

#350 [Language Badge, Language Badge Group]: Check for 1.2 release
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge/language-badge.component.ts
Labels: chore

#352 [Footer, Fieldset, FormSubmitDirective]: Footer logo refactor and fix few bugs
  cypress/e2e/components/alertGroup.cy.ts
  cypress/e2e/components/autocompleteMultiSelect.cy.ts
  cypress/e2e/components/badge.cy.ts
  cypress/e2e/components/breadcrumbs.cy.ts
  cypress/e2e/components/button.cy.ts
  cypress/e2e/components/descriptionList.cy.ts
  cypress/e2e/components/dialog.cy.ts
  cypress/e2e/components/dropdownMenu.cy.ts
  cypress/e2e/components/expandable.cy.ts
  cypress/e2e/components/footer.cy.ts
  cypress/e2e/components/form/autocompleteSingleSelect.cy.ts
  cypress/e2e/components/form/checkboxGroup.cy.ts
  cypress/e2e/components/form/dateRange.cy.ts
  cypress/e2e/components/form/datepicker.cy.ts
  cypress/e2e/components/form/dropdown.cy.ts
  cypress/e2e/components/form/fieldset.cy.ts
  cypress/e2e/components/form/form.cy.ts
  cypress/e2e/components/form/inputWithLanguageOptions.cy.ts
  cypress/e2e/components/form/radioButtonGroup.cy.ts
  cypress/e2e/components/form/textArea.cy.ts
  cypress/e2e/components/form/textInput.cy.ts
  cypress/e2e/components/grid.cy.ts
  cypress/e2e/components/icon.cy.ts
  cypress/e2e/components/link.cy.ts
  cypress/e2e/components/notification.cy.ts
  cypress/e2e/components/section.cy.ts
  cypress/e2e/components/typography/bodytext.cy.ts
  cypress/e2e/components/typography/heading.cy.ts
  cypress/e2e/directives/spacing.cy.ts
  cypress/e2e/directives/tooltip.cy.ts
  cypress/utilities/utility.ts
  ngx-fudis/angular.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/fieldset-base/fieldset-base.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translationKeys.ts
  test/visual-regression/footer.spec.ts-snapshots/footer-1-Mobile-Safari-linux.png
Labels: bug fix

#354 Bump to version v1.2.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#355 [Spacing Classes, DL docs]: Few fixes
  ngx-fudis/projects/ngx-fudis/_index.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-docs.mdx
Labels: chore

#357 [GridUtils]: Adjust replaceAll logic
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/gridUtils.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/rem-converter.ts
Labels: chore

#358 Bump to version v1.2.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#360 Bump to version v1.3.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes
