Repository funidata/fudis, pull requests merged in 2024-12, with the labels that each got.

#497 Add marisanity to CLA allowlist and remove xanxan
  .github/workflows/cla.yaml
Labels: exclude from release notes

#490 [LinkDirective]: Adjust rendering logic
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/assets/i18n/en.json
  ngx-fudis/projects/dev/src/assets/i18n/fi.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-dropdown/select-dropdown.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
Labels: bug fix

#500 [DialogService]: add chaining check for Dialog refs
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
Labels: bug fix

#499 [Storybook]: Adjust Transloco i18n path
  ngx-fudis/.storybook/transloco.module.ts
  ngx-fudis/angular.json
Labels: exclude from release notes

#502 [Error Message]: Change component to directive
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/ngx-fudis.module.ts
  ngx-fudis/projects/ngx-fudis/src/public-api.ts
Labels: breaking change

#495 [Expandable]: Remove default level value
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example-with-multiple-forms.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.stories.ts
Labels: breaking change

#501 [Checkbox Group, Checkbox]: Adjust Checkbox Group's FormGroup and Checkbox's FormControl type
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox/checkbox.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/example/error-summary-example.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example-with-dynamic-validators.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example-with-multiple-forms.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  test/visual-regression/dialog.spec.ts
Labels: breaking change

#506 [Typography]: Add empty state mixin
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/tokens.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/typography.mdx
  ngx-fudis/projects/ngx-fudis/style.scss
  test/visual-regression/dialog.spec.ts
  test/visual-regression/dialog.spec.ts-snapshots/form-3-before-submit-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-3-before-submit-Mobile-Safari-Big-Landscape-linux.png
Labels: improvement

#509 [FudisValidatorUtilities]: Expose utility functions
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-base/select-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validator-utilities.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validator-utilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validators.spec.ts
Labels: feature

#518 [Link Directive]: Changed default size
  ngx-fudis/projects/dev/src/app/app.component.html
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/ngMaterial-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/link/link.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-Mobile-Chrome-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-chromium-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-firefox-linux.png
  test/visual-regression/dialog.spec.ts-snapshots/form-2-errors-webkit-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-Mobile-Chrome-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-Mobile-Safari-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-chromium-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-firefox-linux.png
  test/visual-regression/link.spec.ts-snapshots/link-combinations-1-webkit-linux.png
Labels: bug fix

#519 [ErrorSummary]: Load issue after life cycle hook changes in several components
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/validator-error-message/validator-error-message.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/form/error-summary/internal-error-summary.service.ts
Labels: bug fix

#520 Bump to version v4.0.0-rc.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#521 [Localized Text Group]: Type change
  ngx-fudis/projects/dev/src/app/components/formExamples.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-message/error-message/error-message.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/examples/form-example-with-multiple-forms.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/forms.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validator-utilities.spec.ts
Labels: breaking change

#522 Bump to version v4.0.0-rc.2
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#517 Fix sandbox hot reload
  compose.yaml
  package.json
Labels: exclude from release notes

#526 [Select, Multiselect]: Update missing unit tests
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/autocomplete/autocomplete.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-control-value-accessor/select-control-value-accessor.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
Labels: exclude from release notes
