Repository funidata/fudis, pull requests merged in 2025-01, with the labels that each got.

#528 Bump to version v4.0.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#530 [Icon]: Paperclip icon
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/paperclip.svg
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/icons.ts
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Chrome-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Safari-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-chromium-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-firefox-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-webkit-linux.png
Labels: improvement

#529 [Label]: Height calculation not working properly
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/mixins.scss
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/typography/typography.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/dom/label-height.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/dom/label-height.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/form/validator-utilities.ts
Labels: bug fix

#531 Bump to version v4.1.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#532 [DropdownMenu]: Opened menu overflows the viewport on small screen
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.ts
  test/visual-regression/dropdown-menu.spec.ts
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-dropdown-menu-open-webkit-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/1-init-webkit-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/2-dropdown-menu-option-focused-webkit-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/4-option-clicked-webkit-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/5-option-selected-with-keyboard-webkit-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/6-navigate-to-second-menu-webkit-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-Mobile-Chrome-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-Mobile-Safari-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-chromium-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-firefox-linux.png
  test/visual-regression/dropdown-menu.spec.ts-snapshots/7-close-dropdown-with-escape-webkit-linux.png
Labels: bug fix

#535 [LocalizedTextGroup]: Group label
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.spec.ts
Labels: improvement
