Repository funidata/fudis, pull requests merged in 2025-07, with the labels that each got.

#608 [PeerDependencies]: Change semver syntax to allow newer major versions
  ngx-fudis/projects/documentation/introduction/GettingStarted.mdx
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
Labels: dependencies

#609 Bump to version v6.0.0-rc.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#610 [Release workflow]: Enable multiple major version support
  .github/workflows/delete_branch_docs.yaml
  .github/workflows/publish_docs_from_pr.yaml
  .github/workflows/release.yaml
  ngx-fudis/projects/documentation/development/tooling/Releases.mdx
  package.json
  scripts/release.sh
Labels: github actions

#617 [Icons]: Introducing two new icons
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/exclamation-mark-circle-small.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/exclamation-mark-small.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/info-circle-small.svg
  ngx-fudis/projects/ngx-fudis/src/lib/assets/icons/info-small.svg
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/types/icons.ts
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Chrome-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-Mobile-Safari-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-chromium-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-firefox-linux.png
  test/visual-regression/static-components-playground.spec.ts-snapshots/1-static-components-webkit-linux.png
Labels: breaking change, feature

#618 [Storybook]: URL redirect path
  .github/release.yml
  .github/workflows/release.yaml
Labels: bug fix

#619 [Notification, ErrorSummary]: New aria-describedby attribute
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/nofication.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
Labels: improvement
