Repository funidata/fudis, pull requests merged in 2025-03, with the labels that each got.

#552 [Tooltip]: Accessibility fixes
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.ts
  test/visual-regression/tooltip.spec.ts
Labels: bug fix

#556 Bump to version v4.3.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#555 [Button, Icon, Expandable, Tooltip]: Unit test improvements
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/icon/icon.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.spec.ts
Labels: improvement

#560 [DEPENDENCIES]: Storybook upgrade v8.6.3
  ngx-fudis/.storybook/main.js
  ngx-fudis/.storybook/preview.js
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/documentation/development/InformationSecurityManagement.mdx
  ngx-fudis/projects/documentation/development/tooling/SetupVSCode.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/borders/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/grid/grid-foundations.mdx
Labels: dependencies, chore

#564 Bump to version v5.0.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#562 [Breakpoint Utilities & Service]: Unit tests and documentation
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/breakpoint/breakpoint-service.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/breakpoint/breakpoint.service.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/breakpoint/breakpoint.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/breakpoint/breakpoint-utils.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/breakpoint/breakpoint-utils.ts
Labels: improvement

#565 [DialogService]: Add typings to functions
  ngx-fudis/projects/ngx-fudis/src/lib/services/dialog/dialog.service.ts
Labels: improvement

#566 [Expandable, Fieldset, Footer, Form, Section]:Content projection directives unit tests
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable-content.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/expandable/expandable-content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer-content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/footer/footer.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset-content.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset-content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-content.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/form/form-content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section-content.directive.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/section/section-content.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/miscellaneous.ts
Labels: improvement
