Repository funidata/fudis, pull requests merged in 2025-04, with the labels that each got.

#570 Small updates to and hardening of GitHub Actions workflows
  .github/dependabot.yaml
  .github/workflows/cla.yaml
  .github/workflows/delete_branch_docs.yaml
  .github/workflows/publish_docs_from_pr.yaml
  .github/workflows/release.yaml
  .github/workflows/run_tests.yaml
Labels: chore

#569 [TextArea, TextInput, Label]: Update tests and fix aria-invalid visibility
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/label/label.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-area/text-area.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.component.spec.ts
Labels: chore

#572 [Datepicker]: Update placeholder date abbreviations
  ngx-fudis/projects/ngx-fudis/src/lib/services/translation/translationKeys.ts
  test/visual-regression/datepicker.spec.ts
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-Mobile-Chrome-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-Mobile-Safari-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-chromium-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-firefox-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/10-manual-errors-remove-webkit-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-Mobile-Chrome-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-Mobile-Safari-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-chromium-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-firefox-linux.png
  test/visual-regression/error-summary.spec.ts-snapshots/9-manual-errors-visible-fi-webkit-linux.png
Labels: improvement

#575 [Fudis Core]: Create Core project
  .editorconfig
  .github/workflows/run_tests.yaml
  .stylelintrc.json
  core/README.md
  core/_classes.scss
  core/_component-styles.scss
  core/_index.scss
  core/_mixins.scss
  core/_tokens.scss
  core/package-lock.json
  core/package.json
  core/src/foundations/borders/mixins.scss
  core/src/foundations/borders/tokens.scss
  core/src/foundations/breakpoints/mixins.scss
  core/src/foundations/breakpoints/tokens.scss
  core/src/foundations/colors/mixins.scss
  core/src/foundations/colors/tokens.scss
  core/src/foundations/focus/mixins.scss
  core/src/foundations/focus/tokens.scss
  core/src/foundations/grid/mixins.scss
  core/src/foundations/grid/tokens.scss
  core/src/foundations/spacing/classes.scss
  core/src/foundations/spacing/mixins.scss
  core/src/foundations/spacing/tokens.scss
  core/src/foundations/typography/mixins.scss
  core/src/foundations/typography/tokens.scss
  core/src/foundations/utilities/classes.scss
  core/src/foundations/utilities/mixins.scss
  core/src/foundations/z-index/mixins.scss
  core/src/foundations/z-index/tokens.scss
  ngx-fudis/package.json
  package-lock.json
  package.json
Labels: feature

#578 [Guidance]: Unify maxLength indicator screen reader prompts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
Labels: bug fix

#576 [RadioButtonGroup,CheckboxGroup,Fieldset]: Add help text to Fieldset legend
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/foundations/utilities/mixins.scss
Labels: bug fix

#579 [Button]: CSS class fix for icon-only button
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/button/button.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/popover/popover.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: bug fix

#581 [Notification]: Replace attention text from ARIA to its own hidden paragraph
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/notification.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
  test/visual-regression/error-summary.spec.ts
Labels: bug fix

#582 [LocalizedTextGroup, Select]: Aria-descendants value
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.ts
Labels: bug fix

#583 Bump to version v5.1.0
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes
