Repository funidata/fudis, pull requests merged in 2025-05, with the labels that each got.

#586 [Form Components]: Add control's touched check
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/datepicker/datepicker.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/localized-text-group/localized-text-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select.component.html
Labels: bug fix

#587 [DropdownMenu]: HOTFIX circular dependency
  ngx-fudis/projects/ngx-fudis/src/lib/components/dropdown-menu/dropdown-menu.component.ts
Labels: bug fix

#585 [Chore]: Cleaning Storybook documentation
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/examples/fieldset-example.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/common.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/text-input/text-input.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/notification/readme.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/tab-navigation/tab-navigation.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/storybook.ts
Labels: chore

#588 Bump to version v5.1.1
  ngx-fudis/package-lock.json
  ngx-fudis/package.json
  ngx-fudis/projects/ngx-fudis/package-lock.json
  ngx-fudis/projects/ngx-fudis/package.json
  package-lock.json
  package.json
  test/package-lock.json
  test/package.json
Labels: exclude from release notes

#589 Limit uploaded artifact retention period
  .github/workflows/build_image.yaml
  .github/workflows/run_tests.yaml
Labels: exclude from release notes, github_actions

#592 Fix flaky e2e-tests
  test/visual-regression/error-summary.spec.ts
  test/visual-regression/form-dynamic-validators.spec.ts
Labels: exclude from release notes

#591 [DescriptionList]: Hide compact list commas from DOM
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details-theme.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/theme/component-themes-to-apply.scss
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-Mobile-Chrome-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-Mobile-Safari-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-chromium-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-firefox-linux.png
  test/visual-regression/description-list-with-languages.spec.ts-snapshots/compact-6-clicked-en-badge-webkit-linux.png
Labels: bug fix

#595 [CheckboxGroup, RadioButtonGroup]:Screenreader error messages
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/checkbox-group/checkbox-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/guidance/guidance.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/radio-button-group/radio-button-group.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/id/id.service.ts
Labels: improvement

#596 [Datepicker, DateRange]: Date input parsing fix
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-common/utilities.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/date/date-range/date-range.stories.ts
Labels: bug fix
