Repository funidata/fudis, pull requests merged in 2025-02, with the labels that each got.

#538 [AlertGroup]: Screen overflow fix
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.component.scss
  ngx-fudis/projects/ngx-fudis/src/lib/components/alert/alert-group/alert-group.stories.ts
  test/visual-regression/alert-group.spec.ts
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/1-init-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-add-and-remove-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/2-open-dialog-and-dismiss-alert-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/3-open-dialog-and-dismiss-alert-webkit-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Chrome-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Chrome-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Safari-Big-Landscape-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-Mobile-Safari-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-chromium-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-firefox-linux.png
  test/visual-regression/alert-group.spec.ts-snapshots/4-dismiss-all-webkit-linux.png
Labels: bug fix

#537 [DescriptionList & BodyText]: Lang attribute
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-details/description-list-item-details.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item-term/description-list-item-term.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/description-list/description-list-item/description-list-item.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group-docs.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/components/language-badge-group/language-badge-group.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.html
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/body-text.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/typography/body-text/readme.mdx
Labels: improvement

#542 [SelectOption, MultiSelectOption]: Language change does not update the input value
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/mock_data.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/common/select-option-base/select-option-base.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/multiselect/multiselect-option/multiselect-option.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/select/select/select-option/select-option.component.ts
Labels: bug fix

#546 [Grid]: Correct the type of columns field
  ngx-fudis/projects/ngx-fudis/src/lib/components/grid/grid/grid.stories.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/grid/grid.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/grid/gridUtils.ts
  ngx-fudis/projects/ngx-fudis/src/lib/services/grid/grid-service.mdx
  ngx-fudis/projects/ngx-fudis/src/lib/services/grid/grid.service.ts
  ngx-fudis/projects/ngx-fudis/src/lib/types/grid.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/breakpoint/breakpoint-utils.ts
Labels: bug fix

#545 [Fieldset]: Legend does not get focused when clicking link in ErrorSummary
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/error-summary/error-summary.component.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/form/fieldset/fieldset.component.html
Labels: bug fix

#548 [Tooltip]: Hide Tooltip when it is scrolled out of view
  ngx-fudis/projects/ngx-fudis/src/lib/directives/tooltip/tooltip.directive.ts
  test/visual-regression/tooltip.spec.ts
Labels: bug fix

#550 [Coverage]: Coverage reports to pull requests
  .github/workflows/run_tests.yaml
  ngx-fudis/jest.config.ts
Labels: chore

#551 [Dialog]: Prevent closing a dialog if the button is disabled
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog-directives.spec.ts
  ngx-fudis/projects/ngx-fudis/src/lib/components/dialog/dialog-directives.ts
  ngx-fudis/projects/ngx-fudis/src/lib/directives/form/form-actions/form-actions.directive.ts
  ngx-fudis/projects/ngx-fudis/src/lib/utilities/dialog/dialog-utils.ts
Labels: bug fix
